version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:00'
      timezone: Pacific/Auckland
    groups:
      bun-dependencies:
        patterns:
          - '*'
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:15'
      timezone: Pacific/Auckland
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:30'
      timezone: Pacific/Auckland
    labels:
      - dependencies
      - docker

  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '08:45'
      timezone: Pacific/Auckland
    labels:
      - dependencies
      - docker
